// Electron main process for Equity Research Copilot.
//
// On launch it starts the FastAPI backend (project venv Python) and the Next.js
// production server on free local ports, injects keys from the project's .env
// into the backend, waits until the frontend is serving, then loads it in a
// native window. Both child processes are killed on quit.

const { app, BrowserWindow, dialog, shell } = require("electron");
const { spawn } = require("child_process");
const net = require("net");
const http = require("http");
const path = require("path");
const fs = require("fs");

// Source launches always resolve the adjacent checkout. Packaged local apps
// use machine-specific paths generated by configure-runtime.js before building.
// Keep that generated file out of version control.
let RT = {};
if (app.isPackaged) {
  try {
    RT = require("./runtime-paths.json");
  } catch (_) {
    /* ERC_PROJECT_ROOT can also locate an externally installed checkout. */
  }
}

const PROJECT_ROOT = path.resolve(
  process.env.ERC_PROJECT_ROOT ||
    RT.projectRoot ||
    path.join(__dirname, "..")
);
const VENV_PY = path.join(PROJECT_ROOT, ".venv", "bin", "python");
const FRONTEND_DIR = path.join(PROJECT_ROOT, "frontend");
const NEXT_CLI = path.join(
  FRONTEND_DIR,
  "node_modules",
  "next",
  "dist",
  "bin",
  "next"
);
const CONFIGURED_NODE = process.env.ERC_NODE_PATH
  ? path.resolve(process.env.ERC_NODE_PATH)
  : RT.nodePath;
const USE_ELECTRON_NODE = !(
  CONFIGURED_NODE && fs.existsSync(CONFIGURED_NODE)
);
const NODE_BIN = USE_ELECTRON_NODE ? process.execPath : CONFIGURED_NODE;

let backendProc = null;
let frontendProc = null;
let buildProc = null;
let mainWindow = null;
let appUrl = null;

function getFreePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.unref();
    srv.on("error", reject);
    srv.listen(0, "127.0.0.1", () => {
      const port = srv.address().port;
      srv.close(() => resolve(port));
    });
  });
}

// Minimal .env parser so the AI/FMP keys reach the backend even when launched
// from Finder (no shell environment).
function loadDotenv(file) {
  const out = {};
  try {
    for (const line of fs.readFileSync(file, "utf8").split("\n")) {
      const t = line.trim();
      if (!t || t.startsWith("#")) continue;
      const eq = t.indexOf("=");
      if (eq === -1) continue;
      const k = t.slice(0, eq).trim();
      let v = t.slice(eq + 1).trim();
      if (
        (v.startsWith('"') && v.endsWith('"')) ||
        (v.startsWith("'") && v.endsWith("'"))
      )
        v = v.slice(1, -1);
      if (k) out[k] = v;
    }
  } catch (_) {
    /* no .env is fine */
  }
  return out;
}

// Resolves only on a real 2xx/3xx response; keeps retrying on connection
// refused or 5xx until the timeout. Used to confirm a server is actually
// READY (not merely that the port eventually answered with an error).
function waitForHttp(url, timeoutMs) {
  const start = Date.now();
  return new Promise((resolve, reject) => {
    const retry = () => {
      if (Date.now() - start > timeoutMs)
        reject(new Error("Timed out waiting for " + url));
      else setTimeout(tryOnce, 400);
    };
    const tryOnce = () => {
      const req = http.get(url, (res) => {
        const ok = res.statusCode >= 200 && res.statusCode < 400;
        res.resume();
        if (ok) resolve(true);
        else retry();
      });
      req.on("error", retry);
      req.setTimeout(2500, () => req.destroy());
    };
    tryOnce();
  });
}

function preflight() {
  const problems = [];
  if (!fs.existsSync(VENV_PY))
    problems.push("• Python environment missing (" + VENV_PY + ")");
  if (!fs.existsSync(NEXT_CLI))
    problems.push("• Frontend dependencies missing (frontend/node_modules)");
  // .next is NOT checked here — the app self-heals by building it on launch
  // (see hasProductionBuild/buildFrontend) since `next dev` can clobber it.
  return problems;
}

function pipeLogs(name, proc, onLog) {
  const log = (d) => onLog && onLog(`[${name}] ${d.toString().trim()}`);
  proc.stdout.on("data", log);
  proc.stderr.on("data", log);
  proc.on("exit", (code) => onLog && onLog(`[${name}] exited (code ${code})`));
}

// `next start` requires a PRODUCTION build (.next/BUILD_ID). Running `next dev`
// (e.g. via run_dev.sh) overwrites .next with a dev build that next start can't
// serve, so we detect that and rebuild.
function hasProductionBuild() {
  return fs.existsSync(path.join(FRONTEND_DIR, ".next", "BUILD_ID"));
}

function buildFrontend(onLog) {
  return new Promise((resolve, reject) => {
    const env = { ...process.env, NODE_ENV: "production" };
    if (USE_ELECTRON_NODE) env.ELECTRON_RUN_AS_NODE = "1";
    buildProc = spawn(NODE_BIN, [NEXT_CLI, "build"], { cwd: FRONTEND_DIR, env });
    pipeLogs("build", buildProc, onLog);
    buildProc.on("exit", (code) => {
      buildProc = null; // quitting mid-build must kill it (see killServers)
      code === 0
        ? resolve()
        : reject(new Error("Frontend build failed (code " + code + ")"));
    });
  });
}

// Rejects as soon as a child process dies, so a crashed server surfaces its
// log tail immediately instead of a 3-minute spinner + timeout.
function watchChildExit(name, proc, logTail) {
  return new Promise((_resolve, reject) => {
    proc.on("exit", (code) =>
      reject(
        new Error(
          `${name} exited during startup (code ${code}).\n\nRecent output:\n` +
            logTail().slice(-1200)
        )
      )
    );
  });
}

async function startServers(onLog) {
  const backendPort = await getFreePort();
  const frontendPort = await getFreePort();
  const dotenv = loadDotenv(path.join(PROJECT_ROOT, ".env"));

  // Keep a rolling log tail so startup failures can show WHAT went wrong.
  const logBuf = [];
  const log = (line) => {
    logBuf.push(line);
    if (logBuf.length > 100) logBuf.shift();
    if (onLog) onLog(line);
  };
  const tail = () => logBuf.join("\n");
  onLog = log;

  // Backend first — its heavy imports overlap with any frontend build below.
  backendProc = spawn(
    VENV_PY,
    [
      "-m",
      "uvicorn",
      "backend.app:app",
      "--host",
      "127.0.0.1",
      "--port",
      String(backendPort),
      "--log-level",
      "warning",
    ],
    { cwd: PROJECT_ROOT, env: { ...process.env, ...dotenv, PYTHONUNBUFFERED: "1" } }
  );
  pipeLogs("backend", backendProc, onLog);

  // Self-heal a missing/dev-clobbered production build before next start.
  if (!hasProductionBuild()) {
    if (onLog) onLog("[build] No production build — building the UI (first run)…");
    if (mainWindow) {
      mainWindow.webContents
        .executeJavaScript(
          "var s=document.querySelector('.sub'); if(s){s.textContent='Preparing the app for first launch (building the UI)…';}"
        )
        .catch(() => {});
    }
    await buildFrontend(onLog);
  }

  const fenv = {
    ...process.env,
    BACKEND_URL: `http://127.0.0.1:${backendPort}`,
    PORT: String(frontendPort),
    NODE_ENV: "production",
  };
  if (USE_ELECTRON_NODE) fenv.ELECTRON_RUN_AS_NODE = "1";
  frontendProc = spawn(NODE_BIN, [NEXT_CLI, "start", "-p", String(frontendPort)], {
    cwd: FRONTEND_DIR,
    env: fenv,
  });
  pipeLogs("frontend", frontendProc, onLog);

  // Wait until BOTH servers are truly ready before revealing the dashboard, so
  // an early request can't hit a not-yet-listening backend and 500. Race the
  // health probes against child-process death so a crashed server surfaces
  // its log tail immediately instead of a silent multi-minute spinner.
  const failures = [
    watchChildExit("The valuation backend", backendProc, tail),
    watchChildExit("The frontend server", frontendProc, tail),
  ];
  await Promise.race([
    waitForHttp(`http://127.0.0.1:${backendPort}/api/health`, 180000),
    ...failures,
  ]);
  await Promise.race([
    waitForHttp(`http://127.0.0.1:${frontendPort}/`, 180000),
    ...failures,
  ]);
  return { frontendPort, backendPort };
}

function killServers() {
  for (const p of [backendProc, frontendProc, buildProc]) {
    if (p && !p.killed) {
      try {
        p.kill("SIGTERM");
      } catch (_) {
        /* ignore */
      }
    }
  }
  backendProc = null;
  frontendProc = null;
  buildProc = null;
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1480,
    height: 920,
    minWidth: 1080,
    minHeight: 680,
    backgroundColor: "#080b12",
    title: "Equity Research Copilot",
    // Standard title bar: with "hiddenInset" the dashboard (which has no
    // -webkit-app-region styles) left the window impossible to drag.
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
    },
  });
  mainWindow.loadFile(path.join(__dirname, "loading.html"));

  // Exports (Excel/memo/deck/HTML): save silently to ~/Downloads and reveal in
  // Finder. Without this, blob downloads depend on Electron's default behavior,
  // which can leave the user with no visible result.
  mainWindow.webContents.session.on("will-download", (_event, item) => {
    const dest = uniquePath(
      path.join(app.getPath("downloads"), item.getFilename() || "export")
    );
    item.setSavePath(dest);
    item.once("done", (_e, state) => {
      if (state === "completed") shell.showItemInFolder(dest);
    });
  });

  // News / filing links open in the user's default browser, not the app.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith("http")) shell.openExternal(url);
    return { action: "deny" };
  });
  // Plain target=_blank anchors that navigate the window itself: keep the app
  // pinned to its own localhost UI and push everything else to the browser.
  mainWindow.webContents.on("will-navigate", (event, url) => {
    if (!url.startsWith("http://127.0.0.1") && !url.startsWith("http://localhost")) {
      event.preventDefault();
      if (url.startsWith("http")) shell.openExternal(url);
    }
  });
  // Cmd+R during the loading→dashboard handoff (or a failed load) can strand
  // the window on the loading screen; steer it back to the app once we know
  // the URL.
  mainWindow.webContents.on("did-finish-load", () => {
    const cur = mainWindow.webContents.getURL();
    if (appUrl && cur.startsWith("file://")) mainWindow.loadURL(appUrl);
  });
  mainWindow.webContents.on("did-fail-load", () => {
    if (appUrl) setTimeout(() => mainWindow && mainWindow.loadURL(appUrl), 1000);
  });
  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

// foo.docx -> foo (2).docx if needed, so repeated exports never overwrite.
function uniquePath(p) {
  if (!fs.existsSync(p)) return p;
  const ext = path.extname(p);
  const base = p.slice(0, -ext.length || undefined);
  for (let i = 2; i < 100; i++) {
    const cand = `${base} (${i})${ext}`;
    if (!fs.existsSync(cand)) return cand;
  }
  return p;
}

// Double-launching would spawn a second backend/frontend pair fighting over
// the same store file — focus the existing window instead.
if (!app.requestSingleInstanceLock()) {
  app.quit();
}
app.on("second-instance", () => {
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    mainWindow.focus();
  }
});

app.whenReady().then(async () => {
  createWindow();

  const problems = preflight();
  if (problems.length) {
    dialog.showErrorBox(
      "One-time setup needed",
      "Before the desktop app can run, set up the project once:\n\n" +
        problems.join("\n") +
        "\n\nOpen a terminal in the project folder and run:\n\n  ./run_dev.sh\n\n" +
        "(it installs dependencies and starts the development servers). Stop it " +
        "with Ctrl-C once it prints the URLs, then reopen this app."
    );
    app.quit();
    return;
  }

  try {
    const { frontendPort, backendPort } = await startServers((line) =>
      console.log(line)
    );
    // Pass the backend's actual port to the client (?api=) so it calls the
    // backend directly — the baked production rewrite can't target a dynamic port.
    appUrl = `http://127.0.0.1:${frontendPort}/?api=${backendPort}`;
    console.log("[app] loading " + appUrl);
    if (mainWindow) mainWindow.loadURL(appUrl);
  } catch (e) {
    dialog.showErrorBox("Failed to start", String(e && e.message ? e.message : e));
    app.quit();
  }
});

app.on("activate", () => {
  if (mainWindow === null) createWindow();
});
app.on("window-all-closed", () => app.quit());
app.on("before-quit", killServers);
process.on("exit", killServers);
